apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-init"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "1"
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      restartPolicy: Never
      initContainers:
      - name: pause
        image: busybox
        command: ['sh', '-c', 'while ! nc -z {{ .Release.Name }}-postgresql 5432; do sleep 30; printf "-"; done']
      containers:
      - name: initdb-job
        image: "firezone/firezone:{{ .Chart.AppVersion }}"
        command: ["bin/migrate"]
        securityContext:
          capabilities:
            add: ["NET_ADMIN", "SYS_MODULE"]
        envFrom:
        - configMapRef:
            name: "{{ .Release.Name }}-env"
        - secretRef:
            name: "{{ .Release.Name }}-env"
        volumeMounts:
        - mountPath: /var/firezone
          name: temp-volume
      volumes:
      - name: temp-volume
        emptyDir: {}