apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-env"
type: Opaque
data:
  DEFAULT_ADMIN_EMAIL: {{ .Values.firezone.adminEmail | b64enc | quote }}
  DEFAULT_ADMIN_PASSWORD: {{ .Values.firezone.adminPassword | b64enc | quote }}
  GUARDIAN_SECRET_KEY: {{ printf "Pxj6GcfsSwGmELlsO9md4UA6pMZW7R2JayXOL/aI1W4VCR5GZYF7ir/dPHdDziCr" | b64enc | quote }}
  SECRET_KEY_BASE: {{ printf "5DPqzuS46wYysJ9QZ4aBhSK2hwQu8zw+6PlV5rtaq95AsS3uQdHLCITorycmKlHN" | b64enc | quote }}
  LIVE_VIEW_SIGNING_SALT: {{ printf "qSBbU0e/PWRCoQdDJKPKaSnOawJaKpk4" | b64enc | quote }}
  COOKIE_SIGNING_SALT: {{ printf "JCbf9EtZ" | b64enc | quote }}
  COOKIE_ENCRYPTION_SALT: {{ printf "hZHDTW9O" | b64enc | quote }}
  DATABASE_ENCRYPTION_KEY: {{ printf "G9JChaLxXElL+SepFpNBqW3Ke95+fERz/6FUCSVRnLM=" | b64enc | quote }}
  DATABASE_PASSWORD: {{ .Values.postgresql.auth.password | b64enc | quote }}