apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}"
  {{- with .Values.firezone.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: "{{ .Values.firezone.service.type }}"
  ports:
  - name: wireguard
    port: 51820
    protocol: UDP
    targetPort: wireguard
    nodePort: {{ .Values.firezone.service.ports.wireguard }}
  - name: http
    port: 443
    protocol: TCP
    targetPort: http
    nodePort: {{ .Values.firezone.service.ports.http }}
  selector:
    app: firezone
