apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}"
  {{- with .Values.firezone.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: "{{ .Values.firezone.service.type }}"
  ports:
  - name: wireguard
    port: 51820
    targetPort: wireguard
    protocol: UDP
  - name: http
    port: 443
    targetPort: http
    protocol: TCP
  selector:
    app: firezone
