apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}"
spec:
  type: "{{ .Values.firezone.serviceType }}"
  ports:
  - name: wireguard
    port: 51820
    targetPort: wireguard
    nodePort: 30820
    protocol: UDP
  - name: http
    port: 13000
    targetPort: http
    nodePort: 30080
    protocol: TCP
  selector:
    app: firezone
