firezone:
  adminEmail: "admin@example.com"
  externalUrl: "https://firezone.example.com"
  endpoint: domain:port
  adminPassword: xxxxxxxx
  privateKey: xxxxxxxx

  image:
    repository: firezone/firezone
    pullPolicy: IfNotPresent
    tag: ""

  service:
    type: LoadBalancer
    annotations:

postgresql:
  enabled: true
  auth:
    postgresPassword: xxxxxxxx
    database: firezone
    username: firezone
    password: xxxxxxxxxxx
